### ISSUE TITLE
好久没更新了

### ISSUE THREAD

**Issue by icepy** [iOS-Developer-Documents-Chinese/iOS-Developer-Documents-Chinese#2]
这么好的事情，不做了么？

**Comment by wang820203420** [comment]
心有余而力不足啊，现在想一想，只是我的一厢情愿罢了

------------------ 原始邮件 ------------------
发件人: "Yuntao Chen"; 
发送时间: 2015年11月18日(星期三) 上午10:24
收件人: "iOS-Developer-Documents-Chinese/iOS-Developer-Documents-Chinese";
主题: [iOS-Developer-Documents-Chinese] 好久没更新了 (#2)

这么好的事情，不做了么？

&mdash;
